apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: spring-boot-conventions.packages.kadras.io.0.0.0
spec:
  licenses:
  - Apache 2.0
  refName: spring-boot-conventions.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/package-for-spring-boot-conventions/releases
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - config
      - kbld: {}
  valuesSchema:
    openAPIv3: {}
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: spring-boot-conventions.packages.kadras.io
spec:
  categories:
  - ci/cd
  - configuration
  displayName: spring-boot-conventions
  longDescription: The Spring Boot Convention Server works with the Cartographer Convention
    Controller to apply best-practices to workloads at runtime by understanding the
    developer's intent.
  maintainers:
  - name: Thomas Vitale
  providerName: Kadras
  shortDescription: Spring Boot Convention Server for Cartographer.
  supportDescription: Go to https://kadras.io for documentation and https://github.com/kadras-io/package-for-spring-boot-conventions
    for community support.

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: spring-boot-conventions
spec:
  packageRef:
    refName: spring-boot-conventions.packages.kadras.io
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: kadras-install-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
